/*

  ¿Que es?
  Se trata de un archivo de ejemplo de los loadouts para una mision.

  ¿Es fundamental?
  Si obviamente, sin armas no hay guerra.

  ¿Modificar?
  Lineas 20, 26, 27, 28, 29 y 35 segun el contexto de tu mision.

  ¿Como puedo agregar más?
  Simplemente copia esto...

    Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>NOMBRE DE ESPECIALIDAD</t>", {


      [(call TFAR_fnc_activeSwRadio), 1, "50"] call TFAR_fnc_SetChannelFrequency;
      [(call TFAR_fnc_activeSwRadio), 2, "55"] call TFAR_fnc_SetChannelFrequency;
      [(call TFAR_fnc_activeSwRadio), 3, "60"] call TFAR_fnc_SetChannelFrequency;
      [(call TFAR_fnc_activeSwRadio), 4, "65"] call TFAR_fnc_SetChannelFrequency;
      [(call TFAR_fnc_activeSwRadio), 5, "70"] call TFAR_fnc_SetChannelFrequency;
      [(call TFAR_fnc_activeSwRadio), 6, "75"] call TFAR_fnc_SetChannelFrequency;
      [(call TFAR_fnc_activeSwRadio), 7, "80"] call TFAR_fnc_SetChannelFrequency;
      titleText ["<t color='#58D68D' size='2'>Te Equipaste como...'Piloto de Helicoptero'</t>", "PLAIN DOWN", 1, true, true];
    }, [], 1, true, false, "", "", 5, false, ""];

  y completa los espacios en blanco con los items de la "Especialidad". Recuerda que Armamento_1 es el nombre de la
  variable del objeto a la que se le aplicara la accion para equiparse el loadout de la especialidad.

*/
Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>FUSILERO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "ACE_EntrenchingTool";
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>AMETRALLADOR</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_m60e4";
  player addPrimaryWeaponItem "col_200Rnd_762x51";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "col_200Rnd_762x51";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 4 do {player addItemToBackpack "col_200Rnd_762x51";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "col_scarf2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "ItemRadio";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>SARGENTO 1</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "col_galil_ace22_Laser_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "hgun_Pistol_heavy_01_F";
  player addHandgunItem "optic_MRD";
  player addHandgunItem "11Rnd_45ACP_Mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_EntrenchingTool";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "11Rnd_45ACP_Mag";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>SARGENTO 2</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "col_galil_ace22_Laser_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "hgun_Pistol_heavy_01_F";
  player addHandgunItem "optic_MRD";
  player addHandgunItem "11Rnd_45ACP_Mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_EntrenchingTool";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "11Rnd_45ACP_Mag";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>ANTIEXPLOSIVOS</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "ACE_VMH3";
  player forceAddUniform "bm4jun";
  player addVest "V_PlateCarrierIAGL_dgtl";
  player addWeapon "Binocular";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 6 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  player addItemToVest "SmokeShellRed";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addHeadgear "BR_M88_N";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>RADIO OPERADOR</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "BDF_Alice_radio";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToBackpack "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 5 do {player addItemToBackpack "SmokeShell";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>TIRADOR SELECTO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m14_rail_wd";
  player addPrimaryWeaponItem "ACE_optic_SOS_PIP";
  player addPrimaryWeaponItem "rhsusf_20Rnd_762x51_m80_Mag";
  player addPrimaryWeaponItem "rhsusf_acc_m14_bipod";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "rhsusf_20Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 4 do {player addItemToBackpack "rhsusf_20Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShell";};
  player addItemToBackpack "HandGrenade";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "col_scarf2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>AT</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "rhs_weap_maaws";
  player addSecondaryWeaponItem "rhs_optic_maaws";
  player addSecondaryWeaponItem "rhs_mag_maaws_HEAT";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  for "_i" from 1 to 3 do {player addItemToBackpack "MRAWS_HEAT_F";};
  for "_i" from 1 to 3 do {player addItemToBackpack "MRAWS_HE_F";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>GRANADERO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m4_carryhandle_m203";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "ACE_HuntIR_monitor";
  player addItemToVest "ACE_EntrenchingTool";
  for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToBackpack "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShell";};
  for "_i" from 1 to 7 do {player addItemToBackpack "1Rnd_HE_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_HuntIR_M203";};
  for "_i" from 1 to 3 do {player addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "ACE_40mm_Flare_white";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_40mm_Flare_red";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_40mm_Flare_green";};
  for "_i" from 1 to 5 do {player addItemToBackpack "rhs_mag_M433_HEDP";};
  player addHeadgear "BR_M88_N";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

//condor

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>AMETRALLADOR</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_negev";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "ACE_optic_Hamr_2D";
  player addPrimaryWeaponItem "150Rnd_762x54_Box";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 2 do {player addItemToVest "150Rnd_762x54_Box_Tracer";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "150Rnd_762x54_Box_Tracer";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>PARAMEDICO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "col_galil_ace22_flashlight_glare";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_bag_medcom";
  player addWeapon "Binocular";
  player addItemToUniform "FirstAidKit";
  player addItemToUniform "rhsusf_ANPVS_14";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  player addItemToUniform "kat_Pulseoximeter";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToVest "FirstAidKit";};
  for "_i" from 1 to 7 do {player addItemToVest "col_galil_35rnd_Mk318_SOST_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellYellow";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  player addItemToBackpack "kat_guedel";
  for "_i" from 1 to 8 do {player addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 8 do {player addItemToBackpack "ACE_morphine";};
  player addItemToBackpack "kat_aatKit";
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_packingBandage";};
  player addItemToBackpack "kat_accuvac";
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_quikclot";};
  player addItemToBackpack "ACE_CableTie";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_1 addAction ["<t size='1.5' color='#00C1FF'>MEDICO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_bag_medcom";
  player addWeapon "Binocular";
  player addItemToUniform "FirstAidKit";
  player addItemToUniform "rhsusf_ANPVS_14";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  player addItemToUniform "kat_Pulseoximeter";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToVest "FirstAidKit";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_fieldDressing";};
  player addItemToVest "kat_Pulseoximeter";
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellYellow";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 7 do {player addItemToVest "col_galil_35rnd_Mk318_SOST_mag";};
  player addItemToBackpack "kat_guedel";
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_morphine";};
  player addItemToBackpack "kat_aatKit";
  for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV";};
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 21 do {player addItemToBackpack "ACE_packingBandage";};
  player addItemToBackpack "kat_accuvac";
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_quikclot";};
  player addItemToBackpack "kat_larynx";
  player addItemToBackpack "kat_X_AED";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>FUSILERO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_EntrenchingTool";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>SARGENTO 1</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player addWeapon "hgun_Pistol_heavy_01_F";
  player addHandgunItem "optic_MRD";
  player addHandgunItem "11Rnd_45ACP_Mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 2 do {player addItemToVest "11Rnd_45ACP_Mag";};
  for "_i" from 1 to 6 do {player addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>SARGENTO 2</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player addWeapon "hgun_Pistol_heavy_01_F";
  player addHandgunItem "optic_MRD";
  player addHandgunItem "11Rnd_45ACP_Mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 2 do {player addItemToVest "11Rnd_45ACP_Mag";};
  for "_i" from 1 to 6 do {player addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>GRANADERO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m4_carryhandle_m203";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "ACE_HuntIR_monitor";
  player addItemToVest "ACE_EntrenchingTool";
  for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToBackpack "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShell";};
  for "_i" from 1 to 7 do {player addItemToBackpack "1Rnd_HE_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_HuntIR_M203";};
  for "_i" from 1 to 3 do {player addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "ACE_40mm_Flare_white";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_40mm_Flare_red";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_40mm_Flare_green";};
  for "_i" from 1 to 5 do {player addItemToBackpack "rhs_mag_M433_HEDP";};
  player addHeadgear "BR_M88_N";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>ANTIEXPLOSIVOS</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player addWeapon "ACE_VMH3";
  player forceAddUniform "bm4jun";
  player addVest "V_PlateCarrierIAGL_dgtl";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  player addHeadgear "BR_M88_N";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>RADIO OPERADOR</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "BDF_Alice_radio";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "30Rnd_556x45_Stanag";
  for "_i" from 1 to 6 do {player addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
  player addItemToBackpack "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 5 do {player addItemToBackpack "SmokeShell";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>TIRADOR SELECTO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m14_rail_wd";
  player addPrimaryWeaponItem "ACE_optic_SOS_PIP";
  player addPrimaryWeaponItem "rhsusf_20Rnd_762x51_m80_Mag";
  player addPrimaryWeaponItem "rhsusf_acc_m14_bipod";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "rhsusf_20Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 4 do {player addItemToBackpack "rhsusf_20Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShell";};
  player addItemToBackpack "HandGrenade";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "col_scarf2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>AT</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player addWeapon "rhs_weap_maaws";
  player addSecondaryWeaponItem "rhs_optic_maaws";
  player addSecondaryWeaponItem "rhs_mag_maaws_HEAT";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  for "_i" from 1 to 6 do {player addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
  for "_i" from 1 to 3 do {player addItemToBackpack "MRAWS_HEAT_F";};
  for "_i" from 1 to 3 do {player addItemToBackpack "MRAWS_HE_F";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>PARAMEDICO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_bag_medcom";
  player addWeapon "Binocular";
  player addItemToUniform "FirstAidKit";
  player addItemToUniform "rhsusf_ANPVS_14";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  player addItemToUniform "kat_Pulseoximeter";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToVest "FirstAidKit";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellYellow";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 7 do {player addItemToVest "30Rnd_556x45_Stanag";};
  player addItemToBackpack "kat_guedel";
  for "_i" from 1 to 8 do {player addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 8 do {player addItemToBackpack "ACE_morphine";};
  player addItemToBackpack "kat_aatKit";
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_packingBandage";};
  player addItemToBackpack "kat_accuvac";
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_quikclot";};
  player addItemToBackpack "ACE_CableTie";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_2 addAction ["<t size='1.5' color='#00C1FF'>MEDICO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_tavor";
  player addPrimaryWeaponItem "acc_pointer_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "30Rnd_556x45_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_bag_medcom";
  player addWeapon "Binocular";
  player addItemToUniform "FirstAidKit";
  player addItemToUniform "rhsusf_ANPVS_14";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  player addItemToUniform "kat_Pulseoximeter";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToVest "FirstAidKit";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellYellow";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 7 do {player addItemToVest "30Rnd_556x45_Stanag";};
  player addItemToBackpack "kat_guedel";
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_morphine";};
  player addItemToBackpack "kat_aatKit";
  for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV";};
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 21 do {player addItemToBackpack "ACE_packingBandage";};
  player addItemToBackpack "kat_accuvac";
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_quikclot";};
  player addItemToBackpack "kat_larynx";
  player addItemToBackpack "kat_X_AED";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];
//quetzal

Armamento_3 addAction ["<t size='1.5' color='#00C1FF'>PILOTO CAPITAN</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_mk18_KAC_bk";
  player addPrimaryWeaponItem "rhsusf_acc_compm4";
  player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "BDF_Alice_radio";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToUniform "ACE_salineIV_500";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "kat_Pulseoximeter";
  for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
  player addItemToVest "Chemlight_green";
  player addItemToBackpack "ToolKit";
  player addHeadgear "COL_HeliCrew_Helmet_W";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
  player linkItem "COL_Predator_D";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_3 addAction ["<t size='1.5' color='#00C1FF'>PILOTO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_mk18_KAC_bk";
  player addPrimaryWeaponItem "rhsusf_acc_compm4";
  player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToUniform "ACE_salineIV_500";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToVest "ToolKit";
  for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
  player addItemToVest "Chemlight_green";
  player addHeadgear "COL_HeliCrew_Helmet_W";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
  player linkItem "COL_Predator_D";
}, [], 1, true, false, "", "", 5, false, ""];

//anaconda

Armamento_4 addAction ["<t size='1.5' color='#00C1FF'>CAPITAN TANQUE</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_mk18_KAC_bk";
  player addPrimaryWeaponItem "rhsusf_acc_compm4";
  player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "BDF_Alice_radio";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToUniform "ACE_salineIV_500";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
  player addItemToVest "Chemlight_green";
  player addItemToBackpack "ToolKit";
  player addHeadgear "COL_Crew_Helmet_W";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
  player linkItem "COL_Predator_W";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_4 addAction ["<t size='1.5' color='#00C1FF'>TANQUISTA</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_mk18_KAC_bk";
  player addPrimaryWeaponItem "rhsusf_acc_compm4";
  player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToUniform "ACE_salineIV_500";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToVest "ToolKit";
  for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
  player addItemToVest "Chemlight_green";
  player addHeadgear "COL_Crew_Helmet_W";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

//salamandra

Armamento_5 addAction ["<t size='1.5' color='#00C1FF'>FRANCOTIRADOR</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m24sws_wd";
  player addPrimaryWeaponItem "rhsusf_acc_LEUPOLDMK4_wd";
  player addPrimaryWeaponItem "rhsusf_5Rnd_762x51_m118_special_Mag";
  player addPrimaryWeaponItem "rhsusf_acc_harris_swivel";
  player addWeapon "rhsusf_weap_m9";
  player addHandgunItem "rhsusf_mag_15Rnd_9x19_JHP";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Rangefinder";
  player addItemToUniform "FirstAidKit";
  player addItemToUniform "rhsusf_ANPVS_14";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToUniform "rhsusf_mag_15Rnd_9x19_JHP";
  for "_i" from 1 to 2 do {player addItemToVest "FirstAidKit";};
  player addItemToVest "ACE_MapTools";
  player addItemToVest "ACE_ATragMX";
  player addItemToVest "ACE_DAGR";
  player addItemToVest "ACE_Kestrel4500";
  player addItemToVest "ACE_IR_Strobe_Item";
  player addItemToVest "ACE_Flashlight_XL50";
  player addItemToVest "ACE_RangeCard";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 10 do {player addItemToVest "rhsusf_5Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "ACE_Chemlight_HiGreen";
  for "_i" from 1 to 2 do {player addItemToVest "rhsusf_mag_15Rnd_9x19_JHP";};
  for "_i" from 1 to 2 do {player addItemToBackpack "FirstAidKit";};
  player addItemToBackpack "ACE_Tripod";
  player addItemToBackpack "ACE_SpottingScope";
  for "_i" from 1 to 2 do {player addItemToBackpack "DemoCharge_Remote_Mag";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "ItemRadio";
  player linkItem "ItemGPS";
  player linkItem "COL_Predator_D";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_5 addAction ["<t size='1.5' color='#00C1FF'>TIRADOR SELECTO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m14_rail_wd";
  player addPrimaryWeaponItem "ACE_optic_SOS_PIP";
  player addPrimaryWeaponItem "rhsusf_20Rnd_762x51_m80_Mag";
  player addPrimaryWeaponItem "rhsusf_acc_m14_bipod";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "BDF_Alice_radio";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "rhsusf_20Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  player addItemToBackpack "ACE_ATragMX";
  player addItemToBackpack "ACE_Tripod";
  player addItemToBackpack "ACE_Kestrel4500";
  player addItemToBackpack "ACE_IR_Strobe_Item";
  player addItemToBackpack "ACE_Flashlight_XL50";
  player addItemToBackpack "ACE_RangeCard";
  player addItemToBackpack "ACE_SpottingScope";
  player addItemToBackpack "ACE_MapTools";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "col_scarf2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

//inti takana

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>FUSILERO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "ACE_EntrenchingTool";
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>AMETRALLADOR</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_m60e4";
  player addPrimaryWeaponItem "col_200Rnd_762x51";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "col_200Rnd_762x51";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 4 do {player addItemToBackpack "col_200Rnd_762x51";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "col_scarf2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "ItemRadio";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>SARGENTO 1</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "col_galil_ace22_Laser_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "hgun_Pistol_heavy_01_F";
  player addHandgunItem "optic_MRD";
  player addHandgunItem "11Rnd_45ACP_Mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_EntrenchingTool";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "11Rnd_45ACP_Mag";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>SARGENTO 2</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "col_galil_ace22_Laser_IR";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "hgun_Pistol_heavy_01_F";
  player addHandgunItem "optic_MRD";
  player addHandgunItem "11Rnd_45ACP_Mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_EntrenchingTool";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "11Rnd_45ACP_Mag";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>ANTIEXPLOSIVOS</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "ACE_VMH3";
  player forceAddUniform "bm4jun";
  player addVest "V_PlateCarrierIAGL_dgtl";
  player addWeapon "Binocular";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 6 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  player addItemToVest "SmokeShellRed";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addHeadgear "BR_M88_N";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>RADIO OPERADOR</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "BDF_Alice_radio";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToBackpack "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 5 do {player addItemToBackpack "SmokeShell";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>TIRADOR SELECTO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m14_rail_wd";
  player addPrimaryWeaponItem "ACE_optic_SOS_PIP";
  player addPrimaryWeaponItem "rhsusf_20Rnd_762x51_m80_Mag";
  player addPrimaryWeaponItem "rhsusf_acc_m14_bipod";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "rhsusf_20Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 4 do {player addItemToBackpack "rhsusf_20Rnd_762x51_m62_Mag";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShell";};
  player addItemToBackpack "HandGrenade";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "col_scarf2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>AT</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player addWeapon "rhs_weap_maaws";
  player addSecondaryWeaponItem "rhs_optic_maaws";
  player addSecondaryWeaponItem "rhs_mag_maaws_HEAT";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 6 do {player addItemToVest "col_galil_35rnd_M196_Tracer_Red_mag";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  for "_i" from 1 to 3 do {player addItemToBackpack "MRAWS_HEAT_F";};
  for "_i" from 1 to 3 do {player addItemToBackpack "MRAWS_HE_F";};
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_head_2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>GRANADERO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "rhs_weap_m4_carryhandle_m203";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "rhs_mag_30Rnd_556x45_M855A1_Stanag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_Alice_bag";
  player addWeapon "Binocular";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  player addItemToVest "ACE_HuntIR_monitor";
  player addItemToVest "ACE_EntrenchingTool";
  for "_i" from 1 to 6 do {player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 2 do {player addItemToBackpack "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SmokeShell";};
  for "_i" from 1 to 7 do {player addItemToBackpack "1Rnd_HE_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_HuntIR_M203";};
  for "_i" from 1 to 3 do {player addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "ACE_40mm_Flare_white";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_40mm_Flare_red";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_40mm_Flare_green";};
  for "_i" from 1 to 5 do {player addItemToBackpack "rhs_mag_M433_HEDP";};
  player addHeadgear "BR_M88_N";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>PARAMEDICO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "col_galil_ace22_flashlight_glare";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_bag_medcom";
  player addWeapon "Binocular";
  player addItemToUniform "FirstAidKit";
  player addItemToUniform "rhsusf_ANPVS_14";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  player addItemToUniform "kat_Pulseoximeter";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToVest "FirstAidKit";};
  for "_i" from 1 to 7 do {player addItemToVest "col_galil_35rnd_Mk318_SOST_mag";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellYellow";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  player addItemToBackpack "kat_guedel";
  for "_i" from 1 to 8 do {player addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 8 do {player addItemToBackpack "ACE_morphine";};
  player addItemToBackpack "kat_aatKit";
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_salineIV";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_packingBandage";};
  player addItemToBackpack "kat_accuvac";
  for "_i" from 1 to 20 do {player addItemToBackpack "ACE_quikclot";};
  player addItemToBackpack "ACE_CableTie";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];

Armamento_6 addAction ["<t size='1.5' color='#00C1FF'>MEDICO</t>", {
  if (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "col_galil_ace23";
  player addPrimaryWeaponItem "optic_Hamr";
  player addPrimaryWeaponItem "col_galil_35rnd_Mk318_SOST_mag";
  player forceAddUniform "bm4jun";
  player addVest "Cha_BM4_A_V_L";
  player addBackpack "col_bag_medcom";
  player addWeapon "Binocular";
  player addItemToUniform "FirstAidKit";
  player addItemToUniform "rhsusf_ANPVS_14";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  player addItemToUniform "kat_Pulseoximeter";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToVest "FirstAidKit";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 8 do {player addItemToVest "ACE_fieldDressing";};
  player addItemToVest "kat_Pulseoximeter";
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellYellow";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellBlue";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellRed";};
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShellGreen";};
  for "_i" from 1 to 3 do {player addItemToVest "SmokeShell";};
  player addItemToVest "Chemlight_green";
  for "_i" from 1 to 7 do {player addItemToVest "col_galil_35rnd_Mk318_SOST_mag";};
  player addItemToBackpack "kat_guedel";
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 6 do {player addItemToBackpack "ACE_morphine";};
  player addItemToBackpack "kat_aatKit";
  for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV";};
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 21 do {player addItemToBackpack "ACE_packingBandage";};
  player addItemToBackpack "kat_accuvac";
  for "_i" from 1 to 18 do {player addItemToBackpack "ACE_quikclot";};
  player addItemToBackpack "kat_larynx";
  player addItemToBackpack "kat_X_AED";
  player addHeadgear "colombia_col_casco_lwh_e";
  player addGoggles "shemag_tacticalglass";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "tf_anprc152";
  player linkItem "ItemGPS";
}, [], 1, true, false, "", "", 5, false, ""];
