
/********************************************************************************|
|                             LOADOUTS - DELTA                            |
|********************************************************************************/
_SelectiveShooter = [_this select 0, "<t size='1.5' color='#fbd40b'>Sev(Tirador Selecto)</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "SWLW_DC17M";
  player addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  player addPrimaryWeaponItem "SWLW_attachment_scope_DC17M_sniper";
  player addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  player addWeapon "SWLW_DC15SA";
  player addHandgunItem "SWLW_DC15SA_Mag";
  player forceAddUniform "SWLB_DeltaSev_Uniform";
  player addVest "SWLB_clone_commando_sniper_armor_k1";
  player addBackpack "SWLB_DeltaSev_backpack";
  player addMagazine "Laserbatteries";
  player addWeapon "SWLB_clone_binocular";
  for "_i" from 1 to 3 do {player addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  player addItemToUniform "ACE_RangeCard";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Kestrel4500";
  player addItemToUniform "ACE_MapTools";
  player addItemToUniform "ls_holoprojector_bountyPuck";
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_CableTie";};
  player addItemToUniform "SWLW_beltGrenade_mag";
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_fieldDressing";};
  player addItemToVest "ACE_plasmaIV_500";
  player addItemToBackpack "SWLW_attachment_DC17M_sniper";
  for "_i" from 1 to 10 do {player addItemToBackpack "SWLW_DC17M_Sniper_Mag";};
  for "_i" from 1 to 10 do {player addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SWOP_SCAR_EMP_GrenadeGM";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeGreen";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SWLW_DC15SA_Mag";};
  player addHeadgear "SWLB_DeltaSev_Helmet";
  player addGoggles "lsd_gar_republicCommando_hud";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "ItemGPS";
  player linkItem "SWOP_NVChip2";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;
_ATRiflemanAction = [_this select 0, "<t size='1.5' color='#fbd40b'>Scorch (AT)</t>", {
  _CALLER(!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "SWLW_DC17M";
  player addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  player addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  player addWeapon "SWLW_DC15SA";
  player addHandgunItem "SWLW_DC15SA_Mag";
  player forceAddUniform "SWLB_DeltaScorch_Uniform";
  player addVest "SWLB_clone_commando_eod_armor_k1";
  player addBackpack "SWLB_DeltaScorch_backpack";
  for "_i" from 1 to 3 do {player addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_CableTie";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "SWLW_beltGrenade_mag";
  for "_i" from 1 to 3 do {player addItemToUniform "SWLW_DC15SA_Mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  player addItemToVest "swop_termDetDT_G";
  for "_i" from 1 to 2 do {player addItemToVest "SWOP_SCAR_EMP_GrenadeGM";};
  player addItemToBackpack "SWLW_attachment_DC17M_at";
  for "_i" from 1 to 8 do {player addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 5 do {player addItemToBackpack "SWLW_DC17M_AT_Mag";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SWOP_termDet_G";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeGreen";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeRed";};
  player addItemToBackpack "SWOPthrowablectype";
  player addHeadgear "SWLB_DeltaScorch_Helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;
FE = [_this select 0, "<t size='1.5' color='#fbd40b'>Fixer (Escudos)</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "SWLW_DC17M";
  player addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  player addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  player addWeapon "SWLW_DC15SA";
  player addHandgunItem "SWLW_DC15SA_Mag";
  player forceAddUniform "SWLB_DeltaFixer_Uniform";
  player addVest "SWLB_clone_commando_tech_armor_k1";
  player addBackpack "SWLB_DeltaFixer_backpack";
  player addMagazine "Laserbatteries";
  player addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 3 do {player addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_fieldDressing";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
  player addItemToUniform "JLTS_riot_shield_item";
  player addItemToUniform "SWLW_beltGrenade_mag";
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  player addItemToVest "SWOP_termDet_G";
  for "_i" from 1 to 9 do {player addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 2 do {player addItemToBackpack "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SW_SquadShield_magCARGA";};
  for "_i" from 1 to 3 do {player addItemToBackpack "SWLW_DC15SA_Mag";};
  player addHeadgear "SWLB_DeltaFixer_Helmet";
  player addGoggles "lsd_gar_republicCommando_hud";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "ItemGPS";
  player linkItem "SWLB_DeltaFixer_Antenna";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;
BD = [_this select 0, "<t size='1.5' color='#fbd40b'>Boss (Duales)</t>", {
  _CALLER(!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "SWLW_DC17M";
  player addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  player addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  player addWeapon "ls_weapon_dualDC17_secondary";
  player addHandgunItem "ls_mag_dc17dual_20rnd";
  player addHandgunItem "ls_mag_dc17dual_20rnd";
  player forceAddUniform "SWLB_DeltaBoss_Uniform";
  player addVest "SWLB_clone_commando_sl_armor_k1";
  player addBackpack "SWLB_DeltaBoss_backpack";
  for "_i" from 1 to 3 do {player addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
  player addItemToUniform "SWLW_beltGrenade_mag";
  player addItemToUniform "3AS_SmokeWhite";
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_SmokeGreen";};
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_SmokeBlue";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  player addItemToVest "SWOP_termDet_G";
  player addItemToVest "3AS_SmokeWhite";
  for "_i" from 1 to 9 do {player addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ls_mag_dc17dual_20rnd";};
  player addHeadgear "SWLB_DeltaBoss_Helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;
/* -------------------------- IMAGENES OPCIONALES -------------------------- */

(_this select 0) setUserActionText [_secondAction, "<t size='1.5' color='#fbd40b'>Segundo</t>", "<t size='1.5' color='#fbd40b'>Segundo</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_this select 0) setUserActionText [_riflemanAction, "<t size='1.5' color='#ffff00'>Fusilero</t>", "<t size='1.5' color='#ffff00'>Fusilero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CBI.paa'/>"];
(_this select 0) setUserActionText [_sergeantAction, "<t size='1.5' color='#fbd40b'>Sargento</t>", "<t size='1.5' color='#fbd40b'>Sargento</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_this select 0) setUserActionText [_paramedicAction, "<t size='1.5' color='#ff0000'>Paramédico</t>", "<t size='1.5' color='#ff0000'>Paramédico</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CPM.paa'/>"];
(_this select 0) setUserActionText [_ATRiflemanAction, "<t size='1.5' color='#00ff00'>Fusilero AT</t>", "<t size='1.5' color='#00ff00'>Fusilero AT</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFA.paa'/>"];
(_this select 0) setUserActionText [_MachineGunnerAction, "<t size='1.5' color='#00ff00'>Ametrallador</t>", "<t size='1.5' color='#00ff00'>Ametrallador</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CAL.paa'/>"];
(_this select 0) setUserActionText [_SelectiveShooter, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", "<t size='1.5' color='#00ccff'>Tirador Selecto</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CTS.paa'/>"];
(_this select 0) setUserActionText [_VANTOperatorAction, "<t size='1.5' color='#00ccff'>Operador VANT</t>", "<t size='1.5' color='#00ccff'>Operador VANT</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\OPVNT.paa'/>"];
(_this select 0) setUserActionText [_combatMedicAction, "<t size='1.5' color='#ff0000'>Médico de Combate</t>", "<t size='1.5' color='#ff0000'>Médico de Combate</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CMC.paa'/>"];
(_this select 0) setUserActionText [_radioOperatorAction, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", "<t size='1.5' color='#00ccff'>Operador de Radio</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\COR.paa'/>"];
(_this select 0) setUserActionText [_grenadierRiflemanAction, "<t size='1.5' color='#ffff00'>Fusilero Granadero</t>", "<t size='1.5' color='#ffff00'>Fusilero Granadero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFG.paa'/>"];
