
/********************************************************************************|
|                             LOADOUTS - INFANTERÍA                              |
|********************************************************************************/

_sergeantAction = [_this select 0, "<t size='1.5' color='#fbd40b'>Sargento</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15S_F";
  player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  player addWeapon "ls_weapon_dualDC17_secondary";
  player addHandgunItem "ls_mag_dc17dual_20rnd";
  player addHandgunItem "ls_mag_dc17dual_20rnd";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "JLTS_CloneVestARC";
  player addMagazine "Laserbatteries";
  player addWeapon "SWLB_clone_commander_binocular";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  player addItemToUniform "ls_mag_dc17dual_20rnd";
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToVest "3AS_60Rnd_EC30_mag";};
  player addHeadgear "SWLB_clone_104thSinker_helmet";
  player addGoggles "lsd_gar_p2Interior_hud";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "JLTS_CloneNVGRange_black";
 [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;


_secondAction = [_this select 0, "<t size='1.5' color='#fbd40b'>Segundo</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15S_F";
  player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  player addWeapon "ls_weapon_dualDC17_secondary";
  player addHandgunItem "ls_mag_dc17dual_20rnd";
  player addHandgunItem "ls_mag_dc17dual_20rnd";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "JLTS_CloneVestARC";
  player addMagazine "Laserbatteries";
  player addWeapon "SWLB_clone_commander_binocular";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  player addItemToUniform "ls_mag_dc17dual_20rnd";
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToVest "3AS_60Rnd_EC30_mag";};
  player addHeadgear "SWLB_clone_104thSinker_helmet";
  player addGoggles "lsd_gar_p2Interior_hud";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "JLTS_CloneNVGRange_black";
 [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;


_riflemanAction = [_this select 0, "<t size='1.5' color='#ffff00'>Trooper DC-15A</t>", {
  _CALLER (!local player) exitWith {};
   removeAllWeapons player;
   removeAllItems player;
   removeAllAssignedItems player;
   removeUniform player;
   removeVest player;
   removeBackpack player;
   removeHeadgear player;
   removeGoggles player;
   player addWeapon "3AS_DC15A_F";
   player addPrimaryWeaponItem "3AS_Optic_Red_DC15A";
   player addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
   player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
   player addVest "SWLB_clone_basic_armor";
   for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
   for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
   for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
   for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
   player addItemToUniform "ACE_EarPlugs";
   for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
   player addItemToUniform "ACE_MapTools";
   for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
   player addItemToUniform "ACE_Flashlight_XL50";
   player addItemToUniform "ACE_salineIV_500";
   player addItemToUniform "ACE_EntrenchingTool";
   for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
   for "_i" from 1 to 7 do {player addItemToUniform "3AS_45Rnd_EC50_Mag";};
   for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
   for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
   for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
   for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
   for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
   player addHeadgear "SWLB_clone_104thTrooper_helmet";
   player linkItem "ItemMap";
   player linkItem "ItemCompass";
   player linkItem "ItemWatch";
   player linkItem "SWLB_comlink";
   [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_riflemanAction = [_this select 0, "<t size='1.5' color='#ffff00'>Trooper DC-15C</t>", {
  _CALLER (!local player) exitWith {};
    removeAllWeapons player;
    removeAllItems player;
    removeAllAssignedItems player;
    removeUniform player;
    removeVest player;
    removeBackpack player;
    removeHeadgear player;
    removeGoggles player;
    player addWeapon "3AS_DC15C_F";
    player addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
    player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
    player addVest "SWLB_clone_basic_armor";
    for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
    for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
    for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
    for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
    for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
    player addItemToUniform "ACE_EarPlugs";
    for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
    player addItemToUniform "ACE_MapTools";
    for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
    player addItemToUniform "ACE_Flashlight_XL50";
    player addItemToUniform "ACE_salineIV_500";
    player addItemToUniform "ACE_EntrenchingTool";
    for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
    for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
    for "_i" from 1 to 3 do {player addItemToUniform "3AS_40Rnd_EC40_Mag";};
    for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
    for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
    for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
    for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
    for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
    for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
    for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
    player addHeadgear "SWLB_clone_104thTrooper_helmet";
    player linkItem "ItemMap";
    player linkItem "ItemCompass";
    player linkItem "ItemWatch";
    player linkItem "SWLB_comlink";
    [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_ATRiflemanAction = [_this select 0, "<t size='1.5' color='#00ff00'>Trooper AT</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15C_F";
  player addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
  player addWeapon "3AS_RPS6_HP";
  player addSecondaryWeaponItem "3AS_MK41_AT";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "SWLB_clone_backpack_predef_heavy";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 7 do {player addItemToUniform "3AS_40Rnd_EC40_Mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToBackpack "ACE_splint";};
  player addItemToBackpack "3AS_MK40_AT";
  for "_i" from 1 to 3 do {player addItemToBackpack "3AS_MK41_AT";};
  player addItemToBackpack "3AS_MK42_HE";
  player addHeadgear "SWLB_clone_104thTrooper_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_MachineGunnerAction = [_this select 0, "<t size='1.5' color='#00ff00'>Trooper MG</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "SWLW_Z6";
  player addPrimaryWeaponItem "SWLW_Z6_mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "SWLB_clone_backpack";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {player addItemToUniform "3AS_SmokeGreen";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  for "_i" from 1 to 5 do {player addItemToBackpack "SWLW_Z6_mag";};
  player addHeadgear "SWLB_clone_104thComet_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_grenadierRiflemanAction = [_this select 0, "<t size='1.5' color='#ffff00'> Granadero</t>", {
  _CALLER(!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15A_GL";
  player addPrimaryWeaponItem "3AS_Optic_Red_DC15A";
  player addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "ls_gar_rocket_backpack";
  player addMagazine "Laserbatteries";
  player addWeapon "SWLB_clone_commander_binocular";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 7 do {player addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  for "_i" from 1 to 17 do {player addItemToBackpack "1Rnd_HE_Grenade_shell";};
  for "_i" from 1 to 10 do {player addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
  for "_i" from 1 to 10 do {player addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
  for "_i" from 1 to 10 do {player addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
  for "_i" from 1 to 10 do {player addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";};
  for "_i" from 1 to 5 do {player addItemToBackpack "3AS_45Rnd_EC50_Mag";};
  player addHeadgear "SWLB_clone_104thComet_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "JLTS_CloneNVGRange";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_paramedicAction = [_this select 0, "<t size='1.5' color='#ff0000'>Paramédico</t>", {
   _CALLER (!local player) exitWith {};
   removeAllWeapons player;
   removeAllItems player;
   removeAllAssignedItems player;
   removeUniform player;
   removeVest player;
   removeBackpack player;
   removeHeadgear player;
   removeGoggles player;
   player addWeapon "3AS_DC15C_F";
   player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
   player addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
   player addWeapon "SWLW_DC17";
   player addHandgunItem "SWLW_DC17_Mag";
   player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
   player addVest "SWLB_clone_medic_armor";
   player addBackpack "SWOP_B_CloneBackpack_med";
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_packingBandage";};
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_quikclot";};
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_elasticBandage";};
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_fieldDressing";};
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
   player addItemToUniform "ACE_EarPlugs";
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
   player addItemToUniform "ACE_salineIV_500";
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_morphine";};
   for "_i" from 1 to 3 do {player addItemToUniform "ACE_epinephrine";};
   player addItemToUniform "ACE_Flashlight_XL50";
   for "_i" from 1 to 2 do {player addItemToUniform "Chemlight_green";};
   for "_i" from 1 to 6 do {player addItemToUniform "3AS_40Rnd_EC40_Mag";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_packingBandage";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_quikclot";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_elasticBandage";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_tourniquet";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_CableTie";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
   for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
   for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
   player addItemToVest "SmokeShellGreen";
   player addItemToVest "SmokeShellBlue";
   for "_i" from 1 to 2 do {player addItemToVest "30Rnd_65x39_caseless_mag";};
   for "_i" from 1 to 20 do {player addItemToBackpack "ACE_packingBandage";};
   for "_i" from 1 to 15 do {player addItemToBackpack "ACE_quikclot";};
   for "_i" from 1 to 20 do {player addItemToBackpack "ACE_elasticBandage";};
   for "_i" from 1 to 20 do {player addItemToBackpack "ACE_fieldDressing";};
   for "_i" from 1 to 10 do {player addItemToBackpack "ACE_tourniquet";};
   for "_i" from 1 to 10 do {player addItemToBackpack "ACE_splint";};
   for "_i" from 1 to 20 do {player addItemToBackpack "ACE_morphine";};
   player addItemToBackpack "ACE_surgicalKit";
   for "_i" from 1 to 20 do {player addItemToBackpack "ACE_epinephrine";};
   for "_i" from 1 to 5 do {player addItemToBackpack "ACE_salineIV_500";};
   for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_250";};
   for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV";};
   player addItemToBackpack "ACE_plasmaIV_500";
   for "_i" from 1 to 2 do {player addItemToBackpack "ACE_plasmaIV_250";};
   for "_i" from 1 to 2 do {player addItemToBackpack "kat_chestSeal";};
   for "_i" from 1 to 2 do {player addItemToBackpack "kat_larynx";};
   for "_i" from 1 to 2 do {player addItemToBackpack "kat_aatKit";};
   for "_i" from 1 to 2 do {player addItemToBackpack "kat_guedel";};
   player addItemToBackpack "kat_stethoscope";
   player addItemToBackpack "kat_crossPanel";
   for "_i" from 1 to 5 do {player addItemToBackpack "ACE_bodyBag";};
   player addItemToBackpack "Attachable_Helistretcher";
   for "_i" from 1 to 5 do {player addItemToBackpack "kat_Pulseoximeter";};
   player addHeadgear "SWLB_clone_104thSinker_helmet";
   player addGoggles "SWLB_clone_P2_HUD";
   player linkItem "ItemMap";
   player linkItem "ItemCompass";
   player linkItem "ItemWatch";
   player linkItem "SWLB_comlink";
   [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_combatMedicAction = [_this select 0, "<t size='1.5' color='#ff0000'>Médico de Combate</t>", {
  _CALLER(!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15A_F";
  player addPrimaryWeaponItem "3AS_Muzzle_LE_DC15A";
  player addPrimaryWeaponItem "3AS_Optic_Red_DC15A";
  player addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  player addWeapon "SWLW_DC17";
  player addHandgunItem "SWLW_DC17_Mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_medic_armor";
  player addBackpack "SWOP_B_CloneBackpack_med";
  player addMagazine "Laserbatteries";
  player addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_splint";};
  player addItemToUniform "ACE_salineIV_500";
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 3 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 2 do {player addItemToUniform "Chemlight_green";};
  for "_i" from 1 to 6 do {player addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_tourniquet";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_CableTie";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  player addItemToVest "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
  player addItemToVest "SmokeShellGreen";
  player addItemToVest "SmokeShellBlue";
  player addItemToVest "30Rnd_65x39_caseless_mag";
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_packingBandage";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_quikclot";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_tourniquet";};
  for "_i" from 1 to 5 do {player addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_morphine";};
  player addItemToBackpack "ACE_surgicalKit";
  for "_i" from 1 to 10 do {player addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 5 do {player addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 3 do {player addItemToBackpack "ACE_salineIV";};
  player addItemToBackpack "ACE_plasmaIV_500";
  for "_i" from 1 to 2 do {player addItemToBackpack "ACE_plasmaIV_250";};
  for "_i" from 1 to 10 do {player addItemToBackpack "kat_chestSeal";};
  for "_i" from 1 to 5 do {player addItemToBackpack "kat_larynx";};
  player addItemToBackpack "kat_stethoscope";
  for "_i" from 1 to 10 do {player addItemToBackpack "kat_aatKit";};
  player addItemToBackpack "kat_X_AED";
  player addItemToBackpack "kat_guedel";
  player addItemToBackpack "kat_accuvac";
  player addHeadgear "SWLB_clone_104thComet_helmet";
  player addGoggles "SWLB_clone_P2_HUD";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "ItemGPS";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_SelectiveShooter = [_this select 0, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", {
  _CALLER(!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15A_F";
  player addPrimaryWeaponItem "3AS_Optic_LEScope_DC15A";
  player addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 7 do {player addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addHeadgear "SWLB_clone_104thSinker_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "JLTS_CloneNVG_spec_black";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_radioOperatorAction = [_this select 0, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15C_F";
  player addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "JLTS_Clone_backpack_RTO";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 8 do {player addItemToUniform "3AS_40Rnd_EC40_Mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeGreen";};
  player addHeadgear "SWLB_clone_104thBoost_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

IG = [_this select 0, "<t size='1.5' color='#fbd40b'>Ingeniero de Combate</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15S_F";
  player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "SWLB_clone_backpack_heavy";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 6 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addItemToBackpack "ToolKit";
  player addItemToBackpack "SW_DropTurret_Mag";
  for "_i" from 1 to 4 do {player addItemToBackpack "SW_SquadShield_magCARGA";};
  player addHeadgear "SWLB_clone_eng_helmet";
  player addGoggles "lsd_gar_p2Interior_hud";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "JLTS_CloneNVGRange_black";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

EE = [_this select 0, "<t size='1.5' color='#fbd40b'>Especialista en Explosivos</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15S_F";
  player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "ls_gar_heavy_backpack";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addItemToBackpack "MineDetector";
  player addItemToBackpack "ACE_DefusalKit";
  player addItemToBackpack "ACE_Clacker";
  player addItemToBackpack "SWLW_clones_spec_breach_mag";
  player addItemToBackpack "ls_mag_breach_remoteCharge";
  player addItemToBackpack "JLTS_explosive_emp_50_mag";
  for "_i" from 1 to 3 do {player addItemToBackpack "SWLW_clones_spec_demo_mag";};
  for "_i" from 1 to 2 do {player addItemToBackpack "JLTS_explosive_emp_20_mag";};
  player addHeadgear "SWLB_P2_SpecOps_41st_Helmet";
  player addGoggles "JLTS_Clone_helmetInterior_P2";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;
/* -------------------------- IMAGENES OPCIONALES -------------------------- */

(_this select 0) setUserActionText [_secondAction, "<t size='1.5' color='#fbd40b'>Segundo</t>", "<t size='1.5' color='#fbd40b'>Segundo</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_this select 0) setUserActionText [_riflemanAction, "<t size='1.5' color='#ffff00'>Fusilero</t>", "<t size='1.5' color='#ffff00'>Fusilero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CBI.paa'/>"];
(_this select 0) setUserActionText [_sergeantAction, "<t size='1.5' color='#fbd40b'>Sargento</t>", "<t size='1.5' color='#fbd40b'>Sargento</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_this select 0) setUserActionText [_paramedicAction, "<t size='1.5' color='#ff0000'>Paramédico</t>", "<t size='1.5' color='#ff0000'>Paramédico</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CPM.paa'/>"];
(_this select 0) setUserActionText [_ATRiflemanAction, "<t size='1.5' color='#00ff00'>Fusilero AT</t>", "<t size='1.5' color='#00ff00'>Fusilero AT</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFA.paa'/>"];
(_this select 0) setUserActionText [_MachineGunnerAction, "<t size='1.5' color='#00ff00'>Ametrallador</t>", "<t size='1.5' color='#00ff00'>Ametrallador</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CAL.paa'/>"];
(_this select 0) setUserActionText [_SelectiveShooter, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", "<t size='1.5' color='#00ccff'>Tirador Selecto</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CTS.paa'/>"];
(_this select 0) setUserActionText [_VANTOperatorAction, "<t size='1.5' color='#00ccff'>Operador VANT</t>", "<t size='1.5' color='#00ccff'>Operador VANT</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\OPVNT.paa'/>"];
(_this select 0) setUserActionText [_combatMedicAction, "<t size='1.5' color='#ff0000'>Médico de Combate</t>", "<t size='1.5' color='#ff0000'>Médico de Combate</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CMC.paa'/>"];
(_this select 0) setUserActionText [_radioOperatorAction, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", "<t size='1.5' color='#00ccff'>Operador de Radio</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\COR.paa'/>"];
(_this select 0) setUserActionText [_grenadierRiflemanAction, "<t size='1.5' color='#ffff00'>Fusilero Granadero</t>", "<t size='1.5' color='#ffff00'>Fusilero Granadero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFG.paa'/>"];
