
/********************************************************************************|
|                             LOADOUTS - INFANTERÍA                              |
|********************************************************************************/
 SQ = [_this select 0, "<t size='1.5' color='#00ccff'>Sargento Quetzal</t>", {
   removeAllWeapons _caller;
   removeAllItems _caller;
   removeAllAssignedItems _caller;
   removeUniform _caller;
   removeVest _caller;
   removeBackpack _caller;
   removeHeadgear _caller;
   removeGoggles _caller;
   _caller addWeapon "3AS_DC15S_F";
   _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
   _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
   _caller addWeapon "3AS_DC17STest_F";
   _caller addHandgunItem "3AS_10Rnd_Test_mag";
   _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
   _caller addVest "SWLB_clone_basic_armor";
   _caller addBackpack "JLTS_Clone_backpack_rto_DC";
   _caller addMagazine "Laserbatteries";
   _caller addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
   _caller addItemToUniform "ACE_EarPlugs";
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
   _caller addItemToUniform "ACE_MapTools";
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
   _caller addItemToUniform "ACE_Flashlight_XL50";
   _caller addItemToUniform "ACE_salineIV_500";
   _caller addItemToUniform "ACE_EntrenchingTool";
   for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
   for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "3AS_10Rnd_Test_mag";};
   for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
   for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
   for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
   for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
   _caller addItemToBackpack "ToolKit";
   for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_10Rnd_Test_mag";};
   for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_60Rnd_EC30_mag";};
   _caller addHeadgear "ls_gar_phase2Pilot_helmet";
   _caller addGoggles "SWLB_clone_P2_HUD";
   _caller linkItem "ItemMap";
   _caller linkItem "ItemCompass";
   _caller linkItem "ItemWatch";
   _caller linkItem "SWLB_comlink";
   _caller linkItem "ItemGPS";
   [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 PQ = [_this select 0, "<t size='1.5' color='#00ccff'>Piloto Quetzal</t>", {
   removeAllWeapons _caller;
   removeAllItems _caller;
   removeAllAssignedItems _caller;
   removeUniform _caller;
   removeVest _caller;
   removeBackpack _caller;
   removeHeadgear _caller;
   removeGoggles _caller;
   _caller addWeapon "3AS_DC15S_F";
   _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
   _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
   _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
   _caller addVest "SWLB_clone_basic_armor";
   _caller addBackpack "JLTS_Clone_belt_bag";
   _caller addMagazine "Laserbatteries";
   _caller addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
   _caller addItemToUniform "ACE_EarPlugs";
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
   _caller addItemToUniform "ACE_MapTools";
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
   _caller addItemToUniform "ACE_Flashlight_XL50";
   _caller addItemToUniform "ACE_salineIV_500";
   _caller addItemToUniform "ACE_EntrenchingTool";
   for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
   for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
   for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
   for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
   for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
   for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
   _caller addItemToBackpack "ToolKit";
   _caller addHeadgear "ls_gar_phase2Pilot_helmet";
   _caller linkItem "ItemMap";
   _caller linkItem "ItemCompass";
   _caller linkItem "ItemWatch";
   _caller linkItem "SWLB_comlink";
   _caller linkItem "ItemGPS";
   [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 IQ = [_this select 0, "<t size='1.5' color='#00ccff'>Ingeniero Quetzal</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15S_F";
  _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "SWLB_clone_backpack_heavy";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 6 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addItemToBackpack "ToolKit";
  for "_i" from 1 to 4 do {_caller addItemToBackpack "SW_SquadShield_Mag";};
  _caller addItemToBackpack "SW_PersonalShield_Mag";
  _caller addItemToBackpack "SW_DropTurret_Mag";
  _caller addHeadgear "SWLB_clone_eng_helmet";
  _caller addGoggles "lsd_gar_p2Interior_hud";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "JLTS_CloneNVGRange_black";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 SA = [_this select 0, "<t size='1.5' color='#00ccff'>Sargento Anaconda</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15S_F";
  _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "JLTS_Clone_backpack_rto_DC";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addItemToBackpack "ToolKit";
  _caller addHeadgear "3as_Tanker_Helmet";
  _caller addGoggles "SWLB_clone_P2_HUD";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "ItemGPS";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 TA = [_this select 0, "<t size='1.5' color='#00ccff'>Tripulante Anaconda</t>", {

  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15S_F";
  _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "JLTS_Clone_belt_bag";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addItemToBackpack "ToolKit";
  _caller addHeadgear "3as_Tanker_Helmet";
  _caller addGoggles "SWLB_clone_P2_HUD";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "ItemGPS";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;
