
/********************************************************************************|
|                             LOADOUTS - INFANTERÍA                              |
|********************************************************************************/
 _radioOperatorAction = [_this select 0, "<t size='1.5' color='#00ccff'>Sargento Quetzal</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15S_F";
  player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  player addWeapon "3AS_DC17STest_F";
  player addHandgunItem "3AS_10Rnd_Test_mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "JLTS_Clone_backpack_rto_DC";
  player addMagazine "Laserbatteries";
  player addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 3 do {player addItemToUniform "3AS_10Rnd_Test_mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addItemToBackpack "ToolKit";
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_10Rnd_Test_mag";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_60Rnd_EC30_mag";};
  player addHeadgear "ls_gar_phase2Pilot_helmet";
  player addGoggles "SWLB_clone_P2_HUD";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "ItemGPS";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
  }, [true, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 _radioOperatorAction = [_this select 0, "<t size='1.5' color='#00ccff'>Piloto Quetzal</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15S_F";
  player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "JLTS_Clone_belt_bag";
  player addMagazine "Laserbatteries";
  player addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addItemToBackpack "ToolKit";
  player addHeadgear "ls_gar_phase2Pilot_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "ItemGPS";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 _radioOperatorAction = [_player select 0, "<t size='1.5' color='#00ccff'>Ingeniero Quetzal</t>", {
    _CALLER (!local player) exitWith {};
    removeAllWeapons player;
    removeAllItems player;
    removeAllAssignedItems player;
    removeUniform player;
    removeVest player;
    removeBackpack player;
    removeHeadgear player;
    removeGoggles player;
    player addWeapon "3AS_DC15S_F";
    player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
    player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
    player addVest "SWLB_clone_basic_armor";
    player addBackpack "SWLB_clone_backpack_heavy";
    for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
    for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
    for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
    for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
    for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
    player addItemToUniform "ACE_EarPlugs";
    for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
    player addItemToUniform "ACE_MapTools";
    for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
    player addItemToUniform "ACE_Flashlight_XL50";
    player addItemToUniform "ACE_salineIV_500";
    player addItemToUniform "ACE_EntrenchingTool";
    for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
    for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
    for "_i" from 1 to 6 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
    for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
    for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
    for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
    for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
    for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
    for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
    for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
    player addItemToBackpack "ToolKit";
    for "_i" from 1 to 4 do {player addItemToBackpack "SW_SquadShield_Mag";};
    player addItemToBackpack "SW_PersonalShield_Mag";
    player addItemToBackpack "SW_DropTurret_Mag";
    player addHeadgear "SWLB_clone_eng_helmet";
    player addGoggles "lsd_gar_p2Interior_hud";
    player linkItem "ItemMap";
    player linkItem "ItemCompass";
    player linkItem "ItemWatch";
    player linkItem "SWLB_comlink";
    player linkItem "JLTS_CloneNVGRange_black";
    [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 _radioOperatorAction = [_this select 0, "<t size='1.5' color='#00ccff'>Sargento Anaconda</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15S_F";
  player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "JLTS_Clone_backpack_rto_DC";
  player addMagazine "Laserbatteries";
  player addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addItemToBackpack "ToolKit";
  player addHeadgear "3as_Tanker_Helmet";
  player addGoggles "SWLB_clone_P2_HUD";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "ItemGPS";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

 _radioOperatorAction = [_this select 0, "<t size='1.5' color='#00ccff'>Tripulante Anaconda</t>", {
 _CALLER (!local player) exitWith {};
 removeAllWeapons player;
 removeAllItems player;
 removeAllAssignedItems player;
 removeUniform player;
 removeVest player;
 removeBackpack player;
 removeHeadgear player;
 removeGoggles player;
 player addWeapon "3AS_DC15S_F";
 player addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
 player addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
 player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
 player addVest "SWLB_clone_basic_armor";
 player addBackpack "JLTS_Clone_belt_bag";
 player addMagazine "Laserbatteries";
 player addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
 for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
 for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
 for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
 for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
 for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
 player addItemToUniform "ACE_EarPlugs";
 for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
 player addItemToUniform "ACE_MapTools";
 for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
 player addItemToUniform "ACE_Flashlight_XL50";
 player addItemToUniform "ACE_salineIV_500";
 player addItemToUniform "ACE_EntrenchingTool";
 for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
 for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
 for "_i" from 1 to 3 do {player addItemToUniform "3AS_60Rnd_EC30_mag";};
 for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
 for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
 for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
 for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
 for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
 for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
 for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
 player addItemToBackpack "ToolKit";
 player addHeadgear "3as_Tanker_Helmet";
 player addGoggles "SWLB_clone_P2_HUD";
 player linkItem "ItemMap";
 player linkItem "ItemCompass";
 player linkItem "ItemWatch";
 player linkItem "SWLB_comlink";
 player linkItem "ItemGPS";
 [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;


/* -------------------------- IMAGENES OPCIONALES -------------------------- */

(_player select 0) setUserActionText [_secondAction, "<t size='1.5' color='#fbd40b'>Segundo</t>", "<t size='1.5' color='#fbd40b'>Segundo</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_player select 0) setUserActionText [_riflemanAction, "<t size='1.5' color='#ffff00'>Fusilero</t>", "<t size='1.5' color='#ffff00'>Fusilero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CBI.paa'/>"];
(_player select 0) setUserActionText [_sergeantAction, "<t size='1.5' color='#fbd40b'>Sargento</t>", "<t size='1.5' color='#fbd40b'>Sargento</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_player select 0) setUserActionText [_paramedicAction, "<t size='1.5' color='#ff0000'>Paramédico</t>", "<t size='1.5' color='#ff0000'>Paramédico</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CPM.paa'/>"];
(_player select 0) setUserActionText [_ATRiflemanAction, "<t size='1.5' color='#00ff00'>Fusilero AT</t>", "<t size='1.5' color='#00ff00'>Fusilero AT</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFA.paa'/>"];
(_player select 0) setUserActionText [_MachineGunnerAction, "<t size='1.5' color='#00ff00'>Ametrallador</t>", "<t size='1.5' color='#00ff00'>Ametrallador</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CAL.paa'/>"];
(_player select 0) setUserActionText [_SelectiveShooter, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", "<t size='1.5' color='#00ccff'>Tirador Selecto</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CTS.paa'/>"];
(_player select 0) setUserActionText [_VANTOperatorAction, "<t size='1.5' color='#00ccff'>Operador VANT</t>", "<t size='1.5' color='#00ccff'>Operador VANT</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\OPVNT.paa'/>"];
(_player select 0) setUserActionText [_combatMedicAction, "<t size='1.5' color='#ff0000'>Médico de Combate</t>", "<t size='1.5' color='#ff0000'>Médico de Combate</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CMC.paa'/>"];
(_player select 0) setUserActionText [_radioOperatorAction, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", "<t size='1.5' color='#00ccff'>Operador de Radio</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\COR.paa'/>"];
(_player select 0) setUserActionText [_grenadierRiflemanAction, "<t size='1.5' color='#ffff00'>Fusilero Granadero</t>", "<t size='1.5' color='#ffff00'>Fusilero Granadero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFG.paa'/>"];
