
/********************************************************************************|
|                             LOADOUTS - INFANTERÍA                              |
|********************************************************************************/

_sergeantAction = [_this select 0, "<t size='1.5' color='#fbd40b'>Francotirador</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "SW_iondisruptor_BlasterRifle";
  player addPrimaryWeaponItem "SW_iondisruptor_BlasterRifle_Mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "JLTS_Clone_backpack_s";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  player addItemToUniform "SW_iondisruptor_BlasterRifle_Mag";
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addItemToBackpack "ACE_RangeCard";
  player addItemToBackpack "ACE_SpottingScope";
  for "_i" from 1 to 4 do {player addItemToBackpack "SW_iondisruptor_BlasterRifle_Mag";};
  player addHeadgear "SWLB_clone_ARF_P1_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "JLTS_CloneNVG_spec_black";
 [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;

_SelectiveShooter = [_this select 0, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", {
  _CALLER(!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15A_F";
  player addPrimaryWeaponItem "3AS_Optic_LEScope_DC15A";
  player addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 7 do {player addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  player addHeadgear "SWLB_clone_ARF_P1_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  player linkItem "JLTS_CloneNVG_spec_black";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

_radioOperatorAction = [_this select 0, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", {
  _CALLER (!local player) exitWith {};
  removeAllWeapons player;
  removeAllItems player;
  removeAllAssignedItems player;
  removeUniform player;
  removeVest player;
  removeBackpack player;
  removeHeadgear player;
  removeGoggles player;
  player addWeapon "3AS_DC15C_F";
  player addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
  player forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  player addVest "SWLB_clone_basic_armor";
  player addBackpack "JLTS_Clone_backpack_RTO";
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {player addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_tourniquet";};
  player addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_morphine";};
  player addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {player addItemToUniform "ACE_epinephrine";};
  player addItemToUniform "ACE_Flashlight_XL50";
  player addItemToUniform "ACE_salineIV_500";
  player addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 4 do {player addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 8 do {player addItemToUniform "3AS_40Rnd_EC40_Mag";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {player addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {player addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {player addItemToVest "ACE_splint";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 2 do {player addItemToBackpack "3AS_SmokeGreen";};
  player addHeadgear "SWLB_clone_ARF_P1_helmet";
  player linkItem "ItemMap";
  player linkItem "ItemCompass";
  player linkItem "ItemWatch";
  player linkItem "SWLB_comlink";
  [player,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

/* -------------------------- IMAGENES OPCIONALES -------------------------- */

(_player select 0) setUserActionText [_secondAction, "<t size='1.5' color='#fbd40b'>Segundo</t>", "<t size='1.5' color='#fbd40b'>Segundo</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_player select 0) setUserActionText [_riflemanAction, "<t size='1.5' color='#ffff00'>Fusilero</t>", "<t size='1.5' color='#ffff00'>Fusilero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CBI.paa'/>"];
(_player select 0) setUserActionText [_sergeantAction, "<t size='1.5' color='#fbd40b'>Sargento</t>", "<t size='1.5' color='#fbd40b'>Sargento</t><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CDM.paa'/>"];
(_player select 0) setUserActionText [_paramedicAction, "<t size='1.5' color='#ff0000'>Paramédico</t>", "<t size='1.5' color='#ff0000'>Paramédico</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CPM.paa'/>"];
(_player select 0) setUserActionText [_ATRiflemanAction, "<t size='1.5' color='#00ff00'>Fusilero AT</t>", "<t size='1.5' color='#00ff00'>Fusilero AT</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFA.paa'/>"];
(_player select 0) setUserActionText [_MachineGunnerAction, "<t size='1.5' color='#00ff00'>Ametrallador</t>", "<t size='1.5' color='#00ff00'>Ametrallador</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CAL.paa'/>"];
(_player select 0) setUserActionText [_SelectiveShooter, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", "<t size='1.5' color='#00ccff'>Tirador Selecto</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\CTS.paa'/>"];
(_player select 0) setUserActionText [_VANTOperatorAction, "<t size='1.5' color='#00ccff'>Operador VANT</t>", "<t size='1.5' color='#00ccff'>Operador VANT</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\OPVNT.paa'/>"];
(_player select 0) setUserActionText [_combatMedicAction, "<t size='1.5' color='#ff0000'>Médico de Combate</t>", "<t size='1.5' color='#ff0000'>Médico de Combate</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CMC.paa'/>"];
(_player select 0) setUserActionText [_radioOperatorAction, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", "<t size='1.5' color='#00ccff'>Operador de Radio</t><br/><br/><img size='3' image='\FCLA_Interactions\Insignias\data\COR.paa'/>"];
(_player select 0) setUserActionText [_grenadierRiflemanAction, "<t size='1.5' color='#ffff00'>Fusilero Granadero</t>", "<t size='1.5' color='#ffff00'>Fusilero Granadero</t><br/><img size='4' image='\FCLA_Interactions\Insignias\data\CFG.paa'/>"];
