
/********************************************************************************|
|                             LOADOUTS - INFANTERÍA                              |
|********************************************************************************/

FR = [_this select 0, "<t size='1.5' color='#fbd40b'>Francotirador</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "SW_iondisruptor_BlasterRifle";
  _caller addPrimaryWeaponItem "SW_iondisruptor_BlasterRifle_Mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "JLTS_Clone_backpack_s";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  _caller addItemToUniform "SW_iondisruptor_BlasterRifle_Mag";
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addItemToBackpack "ACE_RangeCard";
  _caller addItemToBackpack "ACE_SpottingScope";
  for "_i" from 1 to 4 do {_caller addItemToBackpack "SW_iondisruptor_BlasterRifle_Mag";};
  _caller addHeadgear "SWLB_clone_ARF_P1_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;

TS = [_this select 0, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15A_F";
  _caller addPrimaryWeaponItem "3AS_Optic_LEScope_DC15A";
  _caller addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addHeadgear "SWLB_clone_ARF_P1_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

RP = [_this select 0, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15C_F";
  _caller addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "JLTS_Clone_backpack_RTO";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 8 do {_caller addItemToUniform "3AS_40Rnd_EC40_Mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeGreen";};
  _caller addHeadgear "SWLB_clone_ARF_P1_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;
