
/********************************************************************************|
|                             LOADOUTS - DELTA                            |
|********************************************************************************/
_SelectiveShooter = [_this select 0, "<t size='1.5' color='#fbd40b'>Sev(Tirador Selecto)</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "SWLW_DC17M";
  _caller addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  _caller addPrimaryWeaponItem "SWLW_attachment_scope_DC17M_sniper";
  _caller addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  _caller addWeapon "SWLW_DC15SA";
  _caller addHandgunItem "SWLW_DC15SA_Mag";
  _caller forceAddUniform "SWLB_DeltaSev_Uniform";
  _caller addVest "SWLB_clone_commando_sniper_armor_k1";
  _caller addBackpack "SWLB_DeltaSev_backpack";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "SWLB_clone_binocular";
  for "_i" from 1 to 3 do {_caller addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  _caller addItemToUniform "ACE_RangeCard";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Kestrel4500";
  _caller addItemToUniform "ACE_MapTools";
  _caller addItemToUniform "ls_holoprojector_bountyPuck";
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_CableTie";};
  _caller addItemToUniform "SWLW_beltGrenade_mag";
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_fieldDressing";};
  _caller addItemToVest "ACE_plasmaIV_500";
  _caller addItemToBackpack "SWLW_attachment_DC17M_sniper";
  for "_i" from 1 to 10 do {_caller addItemToBackpack "SWLW_DC17M_Sniper_Mag";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "SWOP_SCAR_EMP_GrenadeGM";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeGreen";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "SWLW_DC15SA_Mag";};
  _caller addHeadgear "SWLB_DeltaSev_Helmet";
  _caller addGoggles "lsd_gar_republicCommando_hud";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "ItemGPS";
  _caller linkItem "SWOP_NVChip2";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;

_ATRiflemanAction = [_this select 0, "<t size='1.5' color='#fbd40b'>Scorch (AT)</t>", {

  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "SWLW_DC17M";
  _caller addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  _caller addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  _caller addWeapon "SWLW_DC15SA";
  _caller addHandgunItem "SWLW_DC15SA_Mag";
  _caller forceAddUniform "SWLB_DeltaScorch_Uniform";
  _caller addVest "SWLB_clone_commando_eod_armor_k1";
  _caller addBackpack "SWLB_DeltaScorch_backpack";
  for "_i" from 1 to 3 do {_caller addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_CableTie";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "SWLW_beltGrenade_mag";
  for "_i" from 1 to 3 do {_caller addItemToUniform "SWLW_DC15SA_Mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  _caller addItemToVest "swop_termDetDT_G";
  for "_i" from 1 to 2 do {_caller addItemToVest "SWOP_SCAR_EMP_GrenadeGM";};
  _caller addItemToBackpack "SWLW_attachment_DC17M_at";
  for "_i" from 1 to 8 do {_caller addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 5 do {_caller addItemToBackpack "SWLW_DC17M_AT_Mag";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "SWOP_termDet_G";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeGreen";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeRed";};
  _caller addItemToBackpack "SWOPthrowablectype";
  _caller addHeadgear "SWLB_DeltaScorch_Helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;

FE = [_this select 0, "<t size='1.5' color='#fbd40b'>Fixer (Escudos)</t>", {

  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "SWLW_DC17M";
  _caller addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  _caller addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  _caller addWeapon "SWLW_DC15SA";
  _caller addHandgunItem "SWLW_DC15SA_Mag";
  _caller forceAddUniform "SWLB_DeltaFixer_Uniform";
  _caller addVest "SWLB_clone_commando_tech_armor_k1";
  _caller addBackpack "SWLB_DeltaFixer_backpack";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 3 do {_caller addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_fieldDressing";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_splint";};
  _caller addItemToUniform "JLTS_riot_shield_item";
  _caller addItemToUniform "SWLW_beltGrenade_mag";
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  _caller addItemToVest "SWOP_termDet_G";
  for "_i" from 1 to 9 do {_caller addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "SW_SquadShield_magCARGA";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "SWLW_DC15SA_Mag";};
  _caller addHeadgear "SWLB_DeltaFixer_Helmet";
  _caller addGoggles "lsd_gar_republicCommando_hud";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "ItemGPS";
  _caller linkItem "SWLB_DeltaFixer_Antenna";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;

BD = [_this select 0, "<t size='1.5' color='#fbd40b'>Boss (Duales)</t>", {

  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "SWLW_DC17M";
  _caller addPrimaryWeaponItem "SWLW_attachment_DC17M_blaster";
  _caller addPrimaryWeaponItem "SWLW_DC17M_Blaster_Mag";
  _caller addWeapon "ls_weapon_dualDC17_secondary";
  _caller addHandgunItem "ls_mag_dc17dual_20rnd";
  _caller addHandgunItem "ls_mag_dc17dual_20rnd";
  _caller forceAddUniform "SWLB_DeltaBoss_Uniform";
  _caller addVest "SWLB_clone_commando_sl_armor_k1";
  _caller addBackpack "SWLB_DeltaBoss_backpack";
  for "_i" from 1 to 3 do {_caller addItemToUniform "FirstAidKit";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_CableTie";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_splint";};
  _caller addItemToUniform "SWLW_beltGrenade_mag";
  _caller addItemToUniform "3AS_SmokeWhite";
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_SmokeGreen";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_SmokeBlue";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  _caller addItemToVest "SWOP_termDet_G";
  _caller addItemToVest "3AS_SmokeWhite";
  for "_i" from 1 to 9 do {_caller addItemToBackpack "SWLW_DC17M_Blaster_Mag";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "ls_mag_dc17dual_20rnd";};
  _caller addHeadgear "SWLB_DeltaBoss_Helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;
