
/********************************************************************************|
|                             LOADOUTS - INFANTERÍA                              |
|********************************************************************************/

_sergeantAction = [_this select 0, "<t size='1.5' color='#fbd40b'>Sargento</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15S_F";
  _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  _caller addWeapon "ls_weapon_dualDC17_secondary";
  _caller addHandgunItem "ls_mag_dc17dual_20rnd";
  _caller addHandgunItem "ls_mag_dc17dual_20rnd";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "JLTS_CloneVestARC";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "SWLB_clone_commander_binocular";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  _caller addItemToUniform "ls_mag_dc17dual_20rnd";
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  for "_i" from 1 to 5 do {_caller addItemToVest "3AS_60Rnd_EC30_mag";};
  _caller addHeadgear "SWLB_clone_104thSinker_helmet";
  _caller addGoggles "lsd_gar_p2Interior_hud";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "JLTS_CloneNVGRange_black";
 [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;


_secondAction = [_this select 0, "<t size='1.5' color='#fbd40b'>Segundo</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15S_F";
  _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  _caller addWeapon "ls_weapon_dualDC17_secondary";
  _caller addHandgunItem "ls_mag_dc17dual_20rnd";
  _caller addHandgunItem "ls_mag_dc17dual_20rnd";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "JLTS_CloneVestARC";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "SWLB_clone_commander_binocular";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  _caller addItemToUniform "ls_mag_dc17dual_20rnd";
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  for "_i" from 1 to 5 do {_caller addItemToVest "3AS_60Rnd_EC30_mag";};
  _caller addHeadgear "SWLB_clone_104thSinker_helmet";
  _caller addGoggles "lsd_gar_p2Interior_hud";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "JLTS_CloneNVGRange_black";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, true, true], true, "true"] call FCLA_Common_fnc_createLoadout;


_riflemanAction = [_this select 0, "<t size='1.5' color='#ffff00'>Trooper DC-15A</t>", {
   removeAllWeapons _caller;
   removeAllItems _caller;
   removeAllAssignedItems _caller;
   removeUniform _caller;
   removeVest _caller;
   removeBackpack _caller;
   removeHeadgear _caller;
   removeGoggles _caller;
   _caller addWeapon "3AS_DC15A_F";
   _caller addPrimaryWeaponItem "3AS_Optic_Red_DC15A";
   _caller addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
   _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
   _caller addVest "SWLB_clone_basic_armor";
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
   for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
   _caller addItemToUniform "ACE_EarPlugs";
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
   _caller addItemToUniform "ACE_MapTools";
   for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
   _caller addItemToUniform "ACE_Flashlight_XL50";
   _caller addItemToUniform "ACE_salineIV_500";
   _caller addItemToUniform "ACE_EntrenchingTool";
   for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
   for "_i" from 1 to 7 do {_caller addItemToUniform "3AS_45Rnd_EC50_Mag";};
   for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
   for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
   for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
   for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
   for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
   _caller addHeadgear "SWLB_clone_104thTrooper_helmet";
   _caller linkItem "ItemMap";
   _caller linkItem "ItemCompass";
   _caller linkItem "ItemWatch";
   _caller linkItem "SWLB_comlink";
   [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

_riflemanAction = [_this select 0, "<t size='1.5' color='#ffff00'>Trooper DC-15C</t>", {
    removeAllWeapons _caller;
    removeAllItems _caller;
    removeAllAssignedItems _caller;
    removeUniform _caller;
    removeVest _caller;
    removeBackpack _caller;
    removeHeadgear _caller;
    removeGoggles _caller;
    _caller addWeapon "3AS_DC15C_F";
    _caller addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
    _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
    _caller addVest "SWLB_clone_basic_armor";
    for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
    for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
    for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
    for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
    for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
    _caller addItemToUniform "ACE_EarPlugs";
    for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
    _caller addItemToUniform "ACE_MapTools";
    for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
    _caller addItemToUniform "ACE_Flashlight_XL50";
    _caller addItemToUniform "ACE_salineIV_500";
    _caller addItemToUniform "ACE_EntrenchingTool";
    for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
    for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
    for "_i" from 1 to 3 do {_caller addItemToUniform "3AS_40Rnd_EC40_Mag";};
    for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
    for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
    for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
    for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
    for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
    for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
    for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
    _caller addHeadgear "SWLB_clone_104thTrooper_helmet";
    _caller linkItem "ItemMap";
    _caller linkItem "ItemCompass";
    _caller linkItem "ItemWatch";
    _caller linkItem "SWLB_comlink";
    [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

_ATRiflemanAction = [_this select 0, "<t size='1.5' color='#00ff00'>Trooper AT</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15C_F";
  _caller addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
  _caller addWeapon "3AS_RPS6_HP";
  _caller addSecondaryWeaponItem "3AS_MK41_AT";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "SWLB_clone_backpack_predef_heavy";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 7 do {_caller addItemToUniform "3AS_40Rnd_EC40_Mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToBackpack "ACE_splint";};
  _caller addItemToBackpack "3AS_MK40_AT";
  for "_i" from 1 to 3 do {_caller addItemToBackpack "3AS_MK41_AT";};
  _caller addItemToBackpack "3AS_MK42_HE";
  _caller addHeadgear "SWLB_clone_104thTrooper_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

_MachineGunnerAction = [_this select 0, "<t size='1.5' color='#00ff00'>Trooper MG</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "SWLW_Z6";
  _caller addPrimaryWeaponItem "SWLW_Z6_mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "SWLB_clone_backpack";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "3AS_SmokeGreen";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  for "_i" from 1 to 5 do {_caller addItemToBackpack "SWLW_Z6_mag";};
  _caller addHeadgear "SWLB_clone_104thComet_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_grenadierRiflemanAction = [_this select 0, "<t size='1.5' color='#ffff00'> Granadero</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15A_GL";
  _caller addPrimaryWeaponItem "3AS_Optic_Red_DC15A";
  _caller addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "ls_gar_rocket_backpack";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "SWLB_clone_commander_binocular";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  for "_i" from 1 to 17 do {_caller addItemToBackpack "1Rnd_HE_Grenade_shell";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";};
  for "_i" from 1 to 5 do {_caller addItemToBackpack "3AS_45Rnd_EC50_Mag";};
  _caller addHeadgear "SWLB_clone_104thComet_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "JLTS_CloneNVGRange";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_paramedicAction = [_this select 0, "<t size='1.5' color='#ff0000'>Paramédico</t>", {
   removeAllWeapons _caller;
   removeAllItems _caller;
   removeAllAssignedItems _caller;
   removeUniform _caller;
   removeVest _caller;
   removeBackpack _caller;
   removeHeadgear _caller;
   removeGoggles _caller;
   _caller addWeapon "3AS_DC15C_F";
   _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
   _caller addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
   _caller addWeapon "SWLW_DC17";
   _caller addHandgunItem "SWLW_DC17_Mag";
   _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
   _caller addVest "SWLB_clone_medic_armor";
   _caller addBackpack "SWOP_B_CloneBackpack_med";
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_packingBandage";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_quikclot";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_elasticBandage";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_fieldDressing";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_tourniquet";};
   _caller addItemToUniform "ACE_EarPlugs";
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_splint";};
   _caller addItemToUniform "ACE_salineIV_500";
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_morphine";};
   for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_epinephrine";};
   _caller addItemToUniform "ACE_Flashlight_XL50";
   for "_i" from 1 to 2 do {_caller addItemToUniform "Chemlight_green";};
   for "_i" from 1 to 6 do {_caller addItemToUniform "3AS_40Rnd_EC40_Mag";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_packingBandage";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_quikclot";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_elasticBandage";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_fieldDressing";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_tourniquet";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_CableTie";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
   for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
   for "_i" from 1 to 2 do {_caller addItemToVest "SmokeShell";};
   _caller addItemToVest "SmokeShellGreen";
   _caller addItemToVest "SmokeShellBlue";
   for "_i" from 1 to 2 do {_caller addItemToVest "30Rnd_65x39_caseless_mag";};
   for "_i" from 1 to 20 do {_caller addItemToBackpack "ACE_packingBandage";};
   for "_i" from 1 to 15 do {_caller addItemToBackpack "ACE_quikclot";};
   for "_i" from 1 to 20 do {_caller addItemToBackpack "ACE_elasticBandage";};
   for "_i" from 1 to 20 do {_caller addItemToBackpack "ACE_fieldDressing";};
   for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_tourniquet";};
   for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_splint";};
   for "_i" from 1 to 20 do {_caller addItemToBackpack "ACE_morphine";};
   _caller addItemToBackpack "ACE_surgicalKit";
   for "_i" from 1 to 20 do {_caller addItemToBackpack "ACE_epinephrine";};
   for "_i" from 1 to 5 do {_caller addItemToBackpack "ACE_salineIV_500";};
   for "_i" from 1 to 2 do {_caller addItemToBackpack "ACE_salineIV_250";};
   for "_i" from 1 to 3 do {_caller addItemToBackpack "ACE_salineIV";};
   _caller addItemToBackpack "ACE_plasmaIV_500";
   for "_i" from 1 to 2 do {_caller addItemToBackpack "ACE_plasmaIV_250";};
   for "_i" from 1 to 2 do {_caller addItemToBackpack "kat_chestSeal";};
   for "_i" from 1 to 2 do {_caller addItemToBackpack "kat_larynx";};
   for "_i" from 1 to 2 do {_caller addItemToBackpack "kat_aatKit";};
   for "_i" from 1 to 2 do {_caller addItemToBackpack "kat_guedel";};
   _caller addItemToBackpack "kat_stethoscope";
   _caller addItemToBackpack "kat_crossPanel";
   for "_i" from 1 to 5 do {_caller addItemToBackpack "ACE_bodyBag";};
   _caller addItemToBackpack "Attachable_Helistretcher";
   for "_i" from 1 to 5 do {_caller addItemToBackpack "kat_Pulseoximeter";};
   _caller addHeadgear "SWLB_clone_104thSinker_helmet";
   _caller addGoggles "SWLB_clone_P2_HUD";
   _caller linkItem "ItemMap";
   _caller linkItem "ItemCompass";
   _caller linkItem "ItemWatch";
   _caller linkItem "SWLB_comlink";
   [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_combatMedicAction = [_this select 0, "<t size='1.5' color='#ff0000'>Médico de Combate</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15A_F";
  _caller addPrimaryWeaponItem "3AS_Muzzle_LE_DC15A";
  _caller addPrimaryWeaponItem "3AS_Optic_Red_DC15A";
  _caller addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  _caller addWeapon "SWLW_DC17";
  _caller addHandgunItem "SWLW_DC17_Mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_medic_armor";
  _caller addBackpack "SWOP_B_CloneBackpack_med";
  _caller addMagazine "Laserbatteries";
  _caller addWeapon "3AS_JLTS_CloneScoutElectroBinocular";
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_splint";};
  _caller addItemToUniform "ACE_salineIV_500";
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_morphine";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  for "_i" from 1 to 2 do {_caller addItemToUniform "Chemlight_green";};
  for "_i" from 1 to 6 do {_caller addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_tourniquet";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_CableTie";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  _caller addItemToVest "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToVest "SmokeShell";};
  _caller addItemToVest "SmokeShellGreen";
  _caller addItemToVest "SmokeShellBlue";
  _caller addItemToVest "30Rnd_65x39_caseless_mag";
  for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_packingBandage";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_quikclot";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_elasticBandage";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_fieldDressing";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_tourniquet";};
  for "_i" from 1 to 5 do {_caller addItemToBackpack "ACE_splint";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_morphine";};
  _caller addItemToBackpack "ACE_surgicalKit";
  for "_i" from 1 to 10 do {_caller addItemToBackpack "ACE_epinephrine";};
  for "_i" from 1 to 5 do {_caller addItemToBackpack "ACE_salineIV_500";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "ACE_salineIV_250";};
  for "_i" from 1 to 3 do {_caller addItemToBackpack "ACE_salineIV";};
  _caller addItemToBackpack "ACE_plasmaIV_500";
  for "_i" from 1 to 2 do {_caller addItemToBackpack "ACE_plasmaIV_250";};
  for "_i" from 1 to 10 do {_caller addItemToBackpack "kat_chestSeal";};
  for "_i" from 1 to 5 do {_caller addItemToBackpack "kat_larynx";};
  _caller addItemToBackpack "kat_stethoscope";
  for "_i" from 1 to 10 do {_caller addItemToBackpack "kat_aatKit";};
  _caller addItemToBackpack "kat_X_AED";
  _caller addItemToBackpack "kat_guedel";
  _caller addItemToBackpack "kat_accuvac";
  _caller addHeadgear "SWLB_clone_104thComet_helmet";
  _caller addGoggles "SWLB_clone_P2_HUD";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "ItemGPS";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [true, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_SelectiveShooter = [_this select 0, "<t size='1.5' color='#00ccff'>Tirador Selecto</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15A_F";
  _caller addPrimaryWeaponItem "3AS_Optic_LEScope_DC15A";
  _caller addPrimaryWeaponItem "3AS_45Rnd_EC50_Mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "3AS_45Rnd_EC50_Mag";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addHeadgear "SWLB_clone_104thSinker_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "JLTS_CloneNVG_spec_black";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;


_radioOperatorAction = [_this select 0, "<t size='1.5' color='#00ccff'>Operador de Radio</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15C_F";
  _caller addPrimaryWeaponItem "3AS_40Rnd_EC40_Mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "JLTS_Clone_backpack_RTO";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 8 do {_caller addItemToUniform "3AS_40Rnd_EC40_Mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeWhite";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeRed";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeBlue";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "3AS_SmokeGreen";};
  _caller addHeadgear "SWLB_clone_104thBoost_helmet";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, false, false], true, "true"] call FCLA_Common_fnc_createLoadout;

IG = [_this select 0, "<t size='1.5' color='#fbd40b'>Ingeniero de Combate</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15S_F";
  _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "SWLB_clone_backpack_heavy";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 6 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addItemToBackpack "ToolKit";
  _caller addItemToBackpack "SW_DropTurret_Mag";
  for "_i" from 1 to 4 do {_caller addItemToBackpack "SW_SquadShield_magCARGA";};
  _caller addHeadgear "SWLB_clone_eng_helmet";
  _caller addGoggles "lsd_gar_p2Interior_hud";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  _caller linkItem "JLTS_CloneNVGRange_black";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;

EE = [_this select 0, "<t size='1.5' color='#fbd40b'>Especialista en Explosivos</t>", {
  removeAllWeapons _caller;
  removeAllItems _caller;
  removeAllAssignedItems _caller;
  removeUniform _caller;
  removeVest _caller;
  removeBackpack _caller;
  removeHeadgear _caller;
  removeGoggles _caller;
  _caller addWeapon "3AS_DC15S_F";
  _caller addPrimaryWeaponItem "3AS_optic_reflex_DC15C";
  _caller addPrimaryWeaponItem "3AS_60Rnd_EC30_mag";
  _caller forceAddUniform "SWLB_clone_104thTrooper_Uniform";
  _caller addVest "SWLB_clone_basic_armor";
  _caller addBackpack "ls_gar_heavy_backpack";
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_elasticBandage";};
  for "_i" from 1 to 7 do {_caller addItemToUniform "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToUniform "ACE_tourniquet";};
  _caller addItemToUniform "ACE_EarPlugs";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_morphine";};
  _caller addItemToUniform "ACE_MapTools";
  for "_i" from 1 to 5 do {_caller addItemToUniform "ACE_epinephrine";};
  _caller addItemToUniform "ACE_Flashlight_XL50";
  _caller addItemToUniform "ACE_salineIV_500";
  _caller addItemToUniform "ACE_EntrenchingTool";
  for "_i" from 1 to 2 do {_caller addItemToUniform "ACE_splint";};
  for "_i" from 1 to 2 do {_caller addItemToUniform "SWOP_termDet_G";};
  for "_i" from 1 to 3 do {_caller addItemToUniform "3AS_60Rnd_EC30_mag";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_packingBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_quikclot";};
  for "_i" from 1 to 7 do {_caller addItemToVest "ACE_elasticBandage";};
  for "_i" from 1 to 5 do {_caller addItemToVest "ACE_fieldDressing";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_morphine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_epinephrine";};
  for "_i" from 1 to 4 do {_caller addItemToVest "ACE_splint";};
  _caller addItemToBackpack "MineDetector";
  _caller addItemToBackpack "ACE_DefusalKit";
  _caller addItemToBackpack "ACE_Clacker";
  _caller addItemToBackpack "SWLW_clones_spec_breach_mag";
  _caller addItemToBackpack "ls_mag_breach_remoteCharge";
  _caller addItemToBackpack "JLTS_explosive_emp_50_mag";
  for "_i" from 1 to 3 do {_caller addItemToBackpack "SWLW_clones_spec_demo_mag";};
  for "_i" from 1 to 2 do {_caller addItemToBackpack "JLTS_explosive_emp_20_mag";};
  _caller addHeadgear "SWLB_P2_SpecOps_41st_Helmet";
  _caller addGoggles "JLTS_Clone_helmetInterior_P2";
  _caller linkItem "ItemMap";
  _caller linkItem "ItemCompass";
  _caller linkItem "ItemWatch";
  _caller linkItem "SWLB_comlink";
  [_caller,"lsd_imp_clonePurgeHair_head","male12eng"] call BIS_fnc_setIdentity;
}, [false, true, false], true, "true"] call FCLA_Common_fnc_createLoadout;
